"""
second_pass.py

MiniCPU 8-bit CPU Architecture
Assembler - Second Pass

Responsibilities
-----------------

- Resolve labels and EQU symbols.
- Resolve numeric operands.
- Encode 1-byte instructions.
- Encode 2-byte instructions.
- Encode .DB / .BYTE data.
- Generate final machine code.
- Generate address-to-byte mapping.
- Detect undefined symbols.
- Detect invalid operands.
- Validate 8-bit values.

CPU
---

Address space:

    0x00 - 0xFF

Instruction format:

    1-byte instruction:
        [ OPCODE ]

    2-byte instruction:
        [ OPCODE ][ OPERAND ]

Example:

    NOP
        00

    LOAD 0x10
        10 10

    JMP LOOP
        80 <address of LOOP>
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List, Optional

from opcode import OPCODES
from instruction_set import INSTRUCTION_SET

from symbol_table import (
    SymbolTable,
    SymbolTableError,
)


# ============================================================
# CONSTANTS
# ============================================================

BYTE_MIN = 0x00
BYTE_MAX = 0xFF

ADDRESS_MIN = 0x00
ADDRESS_MAX = 0xFF


# ============================================================
# ERRORS
# ============================================================

class SecondPassError(Exception):
    """
    Error raised during assembler second pass.
    """

    def __init__(
        self,
        message: str,
        line: Optional[int] = None,
        column: Optional[int] = None,
    ):
        self.message = message
        self.line = line
        self.column = column

        location = ""

        if line is not None:
            location += f"Line {line}"

        if column is not None:
            location += f", Column {column}"

        if location:
            location += ": "

        super().__init__(
            f"{location}{message}"
        )


# ============================================================
# MACHINE CODE RESULT
# ============================================================

@dataclass
class EncodedLine:
    """
    Machine-code representation of one source line.
    """

    line: int

    address: int

    bytes_: List[int]

    source: str = ""

    label: Optional[str] = None

    instruction: Optional[str] = None

    directive: Optional[str] = None

    @property
    def size(self) -> int:
        """
        Number of generated bytes.
        """

        return len(
            self.bytes_
        )

    @property
    def hex_bytes(self) -> str:
        """
        Return bytes as hexadecimal text.
        """

        return " ".join(
            f"{byte:02X}"
            for byte in self.bytes_
        )


# ============================================================
# SECOND PASS RESULT
# ============================================================

@dataclass
class SecondPassResult:
    """
    Complete assembler output.
    """

    machine_code: bytes

    encoded_lines: List[
        EncodedLine
    ]

    origin: int = 0

    @property
    def size(self) -> int:
        """
        Total machine-code size.
        """

        return len(
            self.machine_code
        )

    @property
    def hex_dump(self) -> str:
        """
        Return machine code as hex.
        """

        return " ".join(
            f"{byte:02X}"
            for byte in self.machine_code
        )


# ============================================================
# SECOND PASS
# ============================================================

class SecondPass:
    """
    MiniCPU assembler second pass.
    """

    def __init__(
        self,
        parsed_lines: Iterable,
        symbol_table: SymbolTable,
        origin: int = 0,
    ):
        self.parsed_lines = list(
            parsed_lines
        )

        self.symbol_table = (
            symbol_table
        )

        self.origin = origin

        self.current_address = (
            origin
        )

        self.output = bytearray()

        self.encoded_lines: List[
            EncodedLine
        ] = []

    # ========================================================
    # RUN
    # ========================================================

    def run(
        self,
    ) -> SecondPassResult:
        """
        Execute second pass.
        """

        self.reset()

        for parsed_line in (
            self.parsed_lines
        ):

            self.process_line(
                parsed_line
            )

        return SecondPassResult(
            machine_code=bytes(
                self.output
            ),
            encoded_lines=(
                self.encoded_lines
            ),
            origin=self.origin,
        )

    # ========================================================
    # RESET
    # ========================================================

    def reset(
        self,
    ) -> None:
        """
        Reset second-pass state.
        """

        self.current_address = (
            self.origin
        )

        self.output = bytearray()

        self.encoded_lines.clear()

    # ========================================================
    # PROCESS LINE
    # ========================================================

    def process_line(
        self,
        parsed_line,
    ) -> Optional[
        EncodedLine
    ]:
        """
        Encode one parsed source line.
        """

        line_number = getattr(
            parsed_line,
            "line",
            0,
        )

        source = getattr(
            parsed_line,
            "source",
            "",
        )

        label = getattr(
            parsed_line,
            "label",
            None,
        )

        instruction = getattr(
            parsed_line,
            "instruction",
            None,
        )

        directive = getattr(
            parsed_line,
            "directive",
            None,
        )

        address = (
            self.current_address
        )

        # ----------------------------------------------------
        # INSTRUCTION
        # ----------------------------------------------------

        if instruction is not None:

            encoded = (
                self.encode_instruction(
                    parsed_line
                )
            )

            result = EncodedLine(
                line=line_number,
                address=address,
                bytes_=encoded,
                source=source,
                label=label,
                instruction=(
                    instruction.upper()
                ),
            )

            self.append_bytes(
                encoded,
                line_number,
            )

            self.encoded_lines.append(
                result
            )

            return result

        # ----------------------------------------------------
        # DIRECTIVE
        # ----------------------------------------------------

        if directive is not None:

            encoded = (
                self.encode_directive(
                    parsed_line
                )
            )

            result = EncodedLine(
                line=line_number,
                address=address,
                bytes_=encoded,
                source=source,
                label=label,
                directive=(
                    directive.upper()
                ),
            )

            if encoded:

                self.append_bytes(
                    encoded,
                    line_number,
                )

            self.encoded_lines.append(
                result
            )

            return result

        # ----------------------------------------------------
        # LABEL ONLY
        # ----------------------------------------------------

        result = EncodedLine(
            line=line_number,
            address=address,
            bytes_=[],
            source=source,
            label=label,
        )

        self.encoded_lines.append(
            result
        )

        return result

    # ========================================================
    # ENCODE INSTRUCTION
    # ========================================================

    def encode_instruction(
        self,
        parsed_line,
    ) -> List[int]:
        """
        Encode an instruction.

        1-byte:

            NOP
            INC
            DEC
            OUT
            IN
            HALT

        2-byte:

            LOAD operand
            STORE operand
            ADD operand
            SUB operand
            AND operand
            OR operand
            XOR operand
            JMP operand
            JZ operand
            CMP operand
        """

        instruction = getattr(
            parsed_line,
            "instruction",
            None,
        )

        if instruction is None:

            return []

        name = (
            instruction.upper()
        )

        line = getattr(
            parsed_line,
            "line",
            None,
        )

        column = getattr(
            parsed_line,
            "column",
            None,
        )

        # ----------------------------------------------------
        # OPCODE CHECK
        # ----------------------------------------------------

        if name not in OPCODES:

            raise SecondPassError(
                (
                    f"Unknown opcode: "
                    f"{name}"
                ),
                line,
                column,
            )

        opcode = OPCODES[
            name
        ]

        # ----------------------------------------------------
        # INSTRUCTION DEFINITION
        # ----------------------------------------------------

        if name not in (
            INSTRUCTION_SET
        ):

            raise SecondPassError(
                (
                    f"Instruction {name} "
                    f"is not defined in "
                    f"instruction_set.py"
                ),
                line,
                column,
            )

        definition = (
            INSTRUCTION_SET[name]
        )

        expected_size = getattr(
            definition,
            "size",
            None,
        )

        if expected_size not in (
            1,
            2,
        ):

            raise SecondPassError(
                (
                    f"Invalid instruction "
                    f"size for {name}: "
                    f"{expected_size}"
                ),
                line,
                column,
            )

        # ----------------------------------------------------
        # OPERANDS
        # ----------------------------------------------------

        operands = getattr(
            parsed_line,
            "operands",
            None,
        )

        if operands is None:

            operands = getattr(
                parsed_line,
                "instruction_operands",
                [],
            )

        operands = list(
            operands or []
        )

        # ----------------------------------------------------
        # 1-BYTE INSTRUCTION
        # ----------------------------------------------------

        if expected_size == 1:

            if operands:

                raise SecondPassError(
                    (
                        f"{name} does not "
                        f"accept an operand"
                    ),
                    line,
                    column,
                )

            return [
                opcode
            ]

        # ----------------------------------------------------
        # 2-BYTE INSTRUCTION
        # ----------------------------------------------------

        if expected_size == 2:

            if len(
                operands
            ) != 1:

                raise SecondPassError(
                    (
                        f"{name} requires "
                        f"exactly one operand"
                    ),
                    line,
                    column,
                )

            operand = operands[
                0
            ]

            value = (
                self.resolve_operand(
                    operand
                )
            )

            return [
                opcode,
                value,
            ]

        raise SecondPassError(
            (
                f"Unsupported instruction "
                f"size: {expected_size}"
            ),
            line,
            column,
        )

    # ========================================================
    # RESOLVE OPERAND
    # ========================================================

    def resolve_operand(
        self,
        operand,
    ) -> int:
        """
        Resolve an operand.

        Supported:

            Decimal:
                10

            Hex:
                0x10

            Binary:
                0b1010

            Character:
                'A'

            Symbol:
                LOOP

            EQU:
                VALUE
        """

        line = getattr(
            operand,
            "line",
            None,
        )

        column = getattr(
            operand,
            "column",
            None,
        )

        # ----------------------------------------------------
        # Already numeric
        # ----------------------------------------------------

        if isinstance(
            operand,
            int,
        ):

            return self.validate_byte(
                operand,
                line,
                column,
            )

        # ----------------------------------------------------
        # Operand object
        # ----------------------------------------------------

        if hasattr(
            operand,
            "is_number",
        ):

            if operand.is_number():

                value = (
                    operand.numeric_value
                )

                return self.validate_byte(
                    value,
                    line,
                    column,
                )

            if operand.is_string():

                value = (
                    operand.value
                )

                if len(
                    value
                ) != 1:

                    raise SecondPassError(
                        (
                            "A character "
                            "operand must "
                            "contain exactly "
                            "one character"
                        ),
                        line,
                        column,
                    )

                return ord(
                    value
                )

            if operand.is_symbol():

                symbol_name = (
                    operand.value
                )

                return (
                    self.resolve_symbol(
                        symbol_name,
                        line,
                        column,
                    )
                )

        # ----------------------------------------------------
        # String
        # ----------------------------------------------------

        if isinstance(
            operand,
            str,
        ):

            text = operand.strip()

            # Hexadecimal

            if text.lower().startswith(
                "0x"
            ):

                try:

                    value = int(
                        text,
                        16,
                    )

                except ValueError:

                    raise SecondPassError(
                        (
                            f"Invalid "
                            f"hexadecimal "
                            f"operand: "
                            f"{text}"
                        ),
                        line,
                        column,
                    )

                return self.validate_byte(
                    value,
                    line,
                    column,
                )

            # Binary

            if text.lower().startswith(
                "0b"
            ):

                try:

                    value = int(
                        text,
                        2,
                    )

                except ValueError:

                    raise SecondPassError(
                        (
                            f"Invalid "
                            f"binary "
                            f"operand: "
                            f"{text}"
                        ),
                        line,
                        column,
                    )

                return self.validate_byte(
                    value,
                    line,
                    column,
                )

            # Decimal

            if text.isdigit():

                return self.validate_byte(
                    int(text),
                    line,
                    column,
                )

            # Character

            if (
                len(text) == 3
                and text[0] == "'"
                and text[-1] == "'"
            ):

                return ord(
                    text[1]
                )

            # Symbol

            return (
                self.resolve_symbol(
                    text,
                    line,
                    column,
                )
            )

        raise SecondPassError(
            (
                f"Cannot resolve "
                f"operand: "
                f"{operand!r}"
            ),
            line,
            column,
        )

    # ========================================================
    # RESOLVE SYMBOL
    # ========================================================

    def resolve_symbol(
        self,
        name: str,
        line: Optional[int] = None,
        column: Optional[int] = None,
    ) -> int:
        """
        Resolve label or EQU.
        """

        try:

            value = (
                self.symbol_table.resolve(
                    name
                )
            )

        except SymbolTableError as error:

            raise SecondPassError(
                str(error),
                line,
                column,
            ) from error

        return self.validate_byte(
            value,
            line,
            column,
        )

    # ========================================================
    # ENCODE DIRECTIVE
    # ========================================================

    def encode_directive(
        self,
        parsed_line,
    ) -> List[int]:
        """
        Encode data directives.

        Supported:

            .DB
            .BYTE
            .ORG
            EQU
        """

        directive = getattr(
            parsed_line,
            "directive",
            "",
        )

        directive = (
            directive.upper()
        )

        operands = getattr(
            parsed_line,
            "directive_operands",
            [],
        )

        line = getattr(
            parsed_line,
            "line",
            None,
        )

        column = getattr(
            parsed_line,
            "column",
            None,
        )

        # ----------------------------------------------------
        # .ORG
        # ----------------------------------------------------

        if directive == ".ORG":

            if len(
                operands
            ) != 1:

                raise SecondPassError(
                    (
                        ".ORG requires "
                        "one operand"
                    ),
                    line,
                    column,
                )

            new_address = (
                self.resolve_operand(
                    operands[0]
                )
            )

            if (
                new_address
                < self.cu
